### ISSUE TITLE
Weekly Timeline : Project Plan

### ISSUE THREAD

**Issue by horizenight** [horizenight/Gsoc24-IfcTester-WebApp#1]
# Project Timeline

## Weekly Schedule

| Week   | Dates               | Work                                                                                                                            | Status |
|--------|---------------------|---------------------------------------------------------------------------------------------------------------------------------|--------|
| Week 1 | 27th May - 2nd June | Project Discussion and Finalization of Features, Development Process, Setting up Daily Sync-Ups, Schedule Meeting with BimVoice, Understand Project Features to develop | [x] |
| Week 2 | 3rd June - 9th June | Implement Backend in FastAPI and IFCTester Library, Make the Frontend Integration with Backend, Display Backend Results on Frontend | [x] |
| Week 3 | 10th - 16th June    | Integrate the WebComponent Logic with the Backend, Replicate the already built functionality to work fine with the FastAPI Backend, ~~Fix the HTML5 API~~ | [x] |
| Week 4 | 17th - 23rd June    | Host the Frontend and Backend and Create a CI/CD pipeline for hosting, ~~Implement IDS Specs Library Feature~~, ~~Implement Error Boundaries (Wrong File Upload)~~                                            | [x] |
| Week 5 | 24th - 30th June    | Discussion on Facet Menu Editor Design, Discussion and Implementation Plan                                                      | [x] |
| Week 6 | 1st - 7th July      | Implement the Facet Menu Editor                                                                                                 | [x] |
| Week 7 | 8th - 13th July     | Implement and incorporate various facets iteratively in the Facet Menu Editor one at a time                                     | [x] |
| Week 8 | 14th - 21st July    | Extend the Backend to fix the Auditing Feature, Discussion on the Frontend Component for the Auditing Feature                   | [x] |
| Week 9 | 22nd - 28th July    | Implement the Auditing Feature Component                                                                                        | [x] |
| Week 10| 29th July - 4th Aug | Project Deployment: Frontend Hosting and Backend Deployment                                                                     | [ ] |
| Week 11| 5th - 11th Aug      | ~~Implementing Additional Features (Based on Discussion at that time), Finishing up the Backlog~~                                  | [x]|
| Week 12| 12th - 18th Aug     | ~~Feedback and Improvement, Finishing Up the Backlog~~                                                                              | [ ] |
| Week 13| 19th - 26th Aug     | Contributor Final Submission                                                                                                    | [ ] |

The timeline is subject to change as per discussion but will be followed more closely.

**Comment by vulevukusej** [comment]
Any reason why this is closed?
