### ISSUE TITLE
Can't create new Applicability or Requirement Facets

### ISSUE THREAD

**Issue by vulevukusej** [horizenight/Gsoc24-IfcTester-WebApp#12]
Steps:

1. Load an existing .ids
2. Hover over + icon
3. Click on any facet
4. Nothing happens.

![image](https://github.com/user-attachments/assets/9385a68c-0fa5-4de8-ab60-ee7fccf841bf)

Additionally, the two "+" icons are positioned so close together, that if both "Applicability" and "Requirements" are empty it becomes impossible to click on anything for the "Applicability" Facet.

**Comment by horizenight** [comment]
Corrected in latest commits.
<img width="187" alt="image" src="https://github.com/user-attachments/assets/75a7b071-67e6-4200-b22d-b28fbd858870">
