### ISSUE TITLE
Some sample IDS files won't load

### ISSUE THREAD

**Issue by vulevukusej** [horizenight/Gsoc24-IfcTester-WebApp#8]
For reference, these files are from the BuildingSmart repository: 

https://github.com/buildingSMART/IDS/releases/tag/v1.0.0

![image](https://github.com/user-attachments/assets/82171936-037d-40c6-8a90-bda68be237cc)

**Comment by vulevukusej** [comment]
Interestingly, when loading these as a library, some specifications load, even with the error.  However, this causes some weird issues with the drag and drop function, whereby dragged specifications override/delete existing specifications.

**Comment by horizenight** [comment]
So I identified the potential issue:
in the get current loading of idsFacet: 
Function`getIdsValue(element)`: 
Takes care of 
1. simpleValue 
2. restriction: pattern 
3. restriction : enumration 

but doesnt take care of: 
4. Restriction : minExclusive and maxExclusive 
ids component:
```
<ids:value>
	<xs:restriction base="xs:double">
		<xs:minExclusive value="0.5"/>
		<xs:maxExclusive value="2.1"/>
	</xs:restriction>
</ids:value>
```

can you guide on how they should look or be rendered ? + more info on this specific restriction

**Comment by horizenight** [comment]
added all the complex restrictions to be taken care of.
